version: '3'

services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mydb
      MYSQL_USER: max
      MYSQL_PASSWORD: max
    ports: [3306]
    volumes:
    - ./mariadb/datadir:/var/lib/mysql

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    container_name: php
    restart: always
    ports:
      - "8081:8081"
      - "8080:8080"
    build:
      context: php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www

  rabbitmq:
    image: library/rabbitmq:3.7-management
    ports: [5672, 15672]
  mailcatcher:
    image: schickling/mailcatcher
    ports: [1025, 1080]